### ISSUE TITLE
Docker Container for API Server

### ISSUE THREAD

**Issue by lassnj** [Laboratoire-de-Chemoinformatique/moodle-qtype_molsimilarity#6]
Hi,
the question type is really interesting. It would be way easier to install if the API Server were available as a Docker Container. Do you know if someone already built a Docker for the API Server? 
Thanks a lot!

**Comment by cperves** [comment]
Hello,
I intend to work on a docker image generated by CI in the next months
I was talking about that last week with my colleague.
I will let you know 
Regards
Céline

**Comment by lassnj** [comment]
Hi,
wow that was quick. Thanks for keeping me informed 😃.
Regards
Julia

**Comment by cperves** [comment]
I can provide you the last docker file that we use on our server

**Comment by lassnj** [comment]
Thanks, that would be great. If you could publish the docker so that we can get your updates as well would support us even better. We plan to make the question type available to our moodle users next school year, so we are not in a big hurry, just thought I'd ask before we produce redundant work.

**Comment by cperves** [comment]
can you contact me on cperves@unistra.fr?

**Comment by cperves** [comment]
docker images can be find here https://github.com/cperves/docker-isida/tree/main
